//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poprigun_DE
{
    using System;
    using System.Collections.Generic;
    
    public partial class agents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public agents()
        {
            this.ProductSale = new HashSet<ProductSale>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_Type_agent { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<double> Phone { get; set; }
        public string Logo { get; set; }
        public string Adress { get; set; }
        public Nullable<double> Priority { get; set; }
        public string CEO { get; set; }
        public Nullable<double> INN { get; set; }
        public Nullable<double> KPP { get; set; }
        public int Amount { get; set; }
    
        public virtual Type_agent Type_agent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSale> ProductSale { get; set; }
    }
}
